name: Tests

on:
  push:
  pull_request:

jobs:
  run_unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python test/unit/test_math_lib.py
  run_func_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: bash test/func/test_add.sh
  run_linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml
          init-shell: bash
      - run: pycodestyle $(git ls-files "*.py")
        shell: bash -l {0}

