rule all:
    input:
        'doc/ascii_rand_scatter.png',
        'doc/ascii_nonrand_scatter.png',
        'doc/ascii_pandp_scatter.png',
        'doc/rolling_rand_scatter.png',
        'doc/rolling_nonrand_scatter.png',
        'doc/rolling_pandp_scatter.png',
        'doc/ascii_rand_histogram.png',
        'doc/ascii_nonrand_histogram.png',
        'doc/ascii_pandp_histogram.png',
        'doc/rolling_rand_histogram.png',
        'doc/rolling_nonrand_histogram.png',
        'doc/rolling_pandp_histogram.png',
        'doc/linear_ascii_rand_insert_time.png',
        'doc/linear_rolling_rand_insert_time.png'

rule plot_hash_scatter:
    input:
        'data/{input_type}_words.txt'
    output:
        'doc/{hash_type}_{input_type}_scatter.png'
    shell:
        """
            python src/hash_functions.py \
                data/{wildcards.input_type}_words.txt {wildcards.hash_type} \
            | python src/scatter.py \
                {output} \
                "Hashed word" \
                "Hashed value"
        """

rule plot_hash_histogram:
    input:
        'data/{input_type}_words.txt'
    output:
        'doc/{hash_type}_{input_type}_histogram.png'
    shell:
        """
            python src/hash_functions.py \
                data/{wildcards.input_type}_words.txt {wildcards.hash_type} \
            | python src/histogram.py \
                {output} \
                "Hashed value" \
                "Freq."
        """

rule sim_hash:
    output:
        '{probe_type}_{hash_type}_{input_type}.{num_inserts}.txt'
    params:
        size = 10000
    shell:
        """
            python src/hash_table.py \
                {params.size} \
                {wildcards.hash_type} \
                {wildcards.probe_type} \
                data/{wildcards.input_type}_words.txt \
                {wildcards.num_inserts}  >  {output}
        """

rule plot_insert_search_scatter:
    input:
        expand('{{probe_type}}_{{hash_type}}_{{input_type}}.{num_inserts}.txt', num_inserts = range(1000,10001,1000))
    output:
        'doc/{probe_type}_{hash_type}_{input_type}_insert_time.png'
    shell:
        """
            grep insert {wildcards.probe_type}_{wildcards.hash_type}_{wildcards.input_type}.*.txt \
            | cut -d " " -f2,3 \
            | python src/scatter.py \
                {output} \
                "Load factor" \
                "Insert time"
        """
